In [1]:
import pandas as pd
import numpy as np
import random
import math
from random import shuffle
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder

In [46]:
data=pd.read_csv('C:\\Users\\Rakesh\\SC\\Project\\mnist\\train.csv')

n=data.iloc[:,1].count()
data=data.iloc[:n//1,:]
n=n//1

ltrain=data.iloc[:,1:]
x = ltrain#.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
ltrain = pd.DataFrame(x_scaled)
ltrain=ltrain.values

ztrain=data.iloc[:,0].values
ztrain.shape=(len(ztrain),1)

onehotencoder=OneHotEncoder(categorical_features=[0])
ztrain=(onehotencoder.fit_transform(ztrain)).toarray()

split=int(0.9*n)

ltest=ltrain[split:]
ztest=ztrain[split:]

ltrain=ltrain[:split]
ztrain=ztrain[:split]


In [58]:
class H_ELM:
    def __init__(self):
        self.B=None  

    def findB(self,H,T):
        Htran=np.transpose(H)
        prod=np.dot(Htran,H)
        row=len(prod)
        col=len(prod[0])
        lam_invmat=np.zeros((row,col),float)
        np.fill_diagonal(lam_invmat,random.random())
        temp=np.sum([lam_invmat,prod],axis=0)
        #print(lam_invmat)
        #print(prod)
        temp=np.linalg.inv(temp)
        B=np.dot(temp,Htran)
        B=np.dot(B,T)
        #print('len=',len(self.layers[-2]))
        #for i in range(len(self.layers[-2])):
            #self.layers[-2][i].weights=[B[i]]
        return B
    
    def sparse_encoder(self,A,b,lam,itrs):
        prod= np.dot(np.transpose(A),A)
        eigvals,eigvecs = np.linalg.eig(prod)
        Li=1/max(eigvals)
        alpha = lam * Li
        m=len(A[1])
        n=len(b[1])
        x=np.zeros((m,n),float)
        yk=x[:][:]
        tk=1
        L1 = 2 * Li * np.array(prod)
        L2 = np.dot(2 * Li * np.array(np.transpose(A)) , np.array(b))
        for i in range(itrs):
            ck= np.array(yk)- np.dot(L1,yk) + np.array(L2)
            x1= np.multiply(np.absolute(ck)-alpha,np.sign(ck))
            tk1= 0.5 + 0.5 * ( (1 + 4 * (tk**2)) ** 0.5 )
            tt = (tk-1)/tk1
            yk = x1 + tt*np.array((np.array(x) - np.array(x1)))
            tk = tk1
            x = x1
        return x
    
    def train2(self,ltrain,ztrain,l):
        bt=[]
        lmd=10**4
        prv=ltrain
        ld=len(ltrain[0])
        for k in range(l):
            b=[[random.uniform(-1,1) for i in range(nl[k])] for j in range(ld)]
            H=np.dot(prv,b)
            beta= np.transpose(self.sparse_encoder(H,prv,lmd,500))
            T=np.dot(prv,beta)
            bt.append(beta)
            prv=T
            ld=nl[k]
        
        #T=np.dot(T,beta)
        B=self.findB(prv,ztrain)
        return [bt,B]
        
    def test2(self,ltest,ztest,beta,B,l):
        inp=ltest
        for k in range(l):
            O=np.dot(inp,beta[k])
            inp=O
        O=np.dot(O,B)
        #print(ztest)
        #print(O3)
        count=0
        for i in range(len(ztest)):
            #print(ztest[i],self.classification(O3[i]),O3[i])
            #print(np.argmax(ztest[i]),np.argmax(O3[i]))
            if np.argmax(ztest[i])==np.argmax(O[i]):
                count+=1
        print('accuracy=',100*count/len(ztest))
        
M=H_ELM()
l=2
nl=[100,100]
[beta,B]=M.train2(ltrain,ztrain,l)
#print(np.matrix(beta[0]))
M.test2(ltest,ztest,beta,B,l)

accuracy= 74.23809523809524


In [17]:
l=np.array([1,2,3])
l.shape=(len(l),1)

In [18]:
print(l)

[[1]
 [2]
 [3]]


In [23]:
ztrain[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
len(beta)

301

In [43]:
l=np.array([5,2,3])
np.argmax(l)

0

In [36]:
ztest[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.array([1,2,3])==np.array([1,2,3])

array([ True,  True,  True])

In [59]:
import time
t1=time.time()
len(ltrain[0])
t2=time.time()
print(t2-t1)

784